version: "3.8"

services:
  php81: &base
    build:
      context: docker/
      args:
        PHP_IMAGE: php:8.1
        XDEBUG: xdebug-3.1.5
    volumes:
      - .:/home/dev/lib
    tty: true
    user: dev
    working_dir: /home/dev/lib
  php82:
    <<: *base
    build:
      context: docker/
      args:
        PHP_IMAGE: php:8.2
  php83:
    <<: *base
    build:
      context: docker/
      args:
        PHP_IMAGE: php:8.3
