services:
  php81: &base
    build:
      context: docker/
      args:
        PHP_IMAGE: php:8.1
    volumes:
      - .:/home/dev/lib
    tty: true
    user: dev
    working_dir: /home/dev/lib

  php82:
    <<: *base
    build:
      context: docker/
      args:
        PHP_IMAGE: php:8.2

  php83:
    <<: *base
    build:
      context: docker/
      args:
        PHP_IMAGE: php:8.3

  php84:
    <<: *base
    build:
      context: docker/
      args:
        PHP_IMAGE: php:8.4
