name: CI

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.0, 8.1, 8.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
      - name: Run tests
        run: ./vendor/bin/phpunit --coverage-clover=build/coverage-report.xml
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          file: build/coverage-report.xml
