name: Static analysis

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  job:
    strategy:
      matrix:
        include:
          - description: Validate composer.json
            script: composer validate
          - description: Code style
            script: make cs-check
          - description: PSalm
            script: make psalm
          - description: Type assertions
            script: make type-assertions
          - description: Architecture assertions
            script: make architecture

    name: ${{ matrix.description }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
      - run: ${{ matrix.script }}

  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: typos-action
        uses: crate-ci/typos@v1.0.4
